### ISSUE TITLE
All mods show "This mod does not have any configuration keys" after selecting a mod with no config options.

### ISSUE THREAD

**Issue by Raidriar796** [badhaloninja/ResoniteModSettings#1]
When `Show mods without config items` is enabled, clicking any mod without a config will cause the message "This mod does not have any configuration keys" to appear on every mod's config list. This returns to normal behavior once you click the ResoniteModSettings settings.

**Comment by badhaloninja** [comment]
What mods were you observing this behavior with?

**Comment by Nytra** [comment]
This is sometimes happening to me when I click between mod tabs too rapidly. Some mods which I know have configs will show the no config screen.

**Comment by Raidriar796** [comment]
> What mods were you observing this behavior with?

I was experiencing this with my own port of ShowDriveSource and MotionBlurDisable. There is a chance I messed up something when porting them but others were saying it happens to them too so I'm not sure.

**Comment by Raidriar796** [comment]
With more testing, I found that enabling `Highlight alternate configuration items` fixes the issue, so I'm thinking that setting being disabled is potentially interferring with configs being refreshed.

**Comment by badhaloninja** [comment]
Fixed in v2.0.2
