### ISSUE TITLE
keys created using configuration builder don't show up at all

### ISSUE THREAD

**Issue by art0007i** [badhaloninja/ResoniteModSettings#2]
on the latest version of ResoniteModSettings one of my mods ([DefaultToolOverride](https://github.com/art0007i/DefaultToolOverride/blob/master/DefaultToolOverride/DefaultToolOverride.cs#L75)) shows no config options.
My best guess is that it's because of the 2.1.0 update which introduced `passing field attributes to SyncMemberEditorBuilder` but my config options don't even have fields at all.

and in general I think instead of passing field attributes you should actually aim in the direction of allowing fully custom ui for mods settings by passing a ui builder to them at ui generation time.

**Comment by badhaloninja** [comment]
There are plans to allow fully custom ui,
there's no reason not to allow people to just define field attributes along side fully custom ui for those who wouldn't want to make their own ui

I did not know you could manually define configuration keys like this, I'll add a null check for now

**Comment by badhaloninja** [comment]
Fixed in v2.1.2
